// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  R2_BUCKET?: R2Bucket;
  PASSWORD?: string;
  SECRET_KEY?: string;
  STORAGE_PROVIDER?: string;
  TELEGRAPH_SIGN_ENABLED?: string;
  MAX_IMAGE_SIZE?: string
  ENABLE_IMAGE_COMPRESSION?: string
  COMPRESSED_IMAGE_MAX_SIZE?: string
  MAX_IMAGE_WIDTH_OR_HEIGHT?: string
}
