// Generated by Wrangler
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  R2_BUCKET: R2Bucket;
  PASSWORD: string;
  SECRET_KEY: string;
  STORAGE_PROVIDER: string;
  TELEGRAPH_SIGN_ENABLED: string;
}
