/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZiWewdKRPa9
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Inter } from 'next/font/google'

 inter({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import Link from 'next/link';
import { MountainIcon } from '@/app/components/icon/mountain';
import { GithubIcon } from '@/app/components/icon/github';
import { Button } from '@/app/components/ui/button';

export function Navbar() {
  return (
    <header className="flex h-16 w-full absolute top-0">
      <div
        className="container mx-auto max-w-screen-lg flex h-16 w-full items-center justify-between bg-background px-4 md:px-6">
        <Link href="/" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">山</span>
        </Link>
        <Button variant="ghost" size="icon" className="ml-auto" asChild>
          <Link href="https://github.com/mx1700/cloudflare-image-share" target="_blank" className="flex items-center gap-2" prefetch={false}>
            <GithubIcon className="h-6 w-6" />
            <span className="sr-only">GitHub</span>
          </Link>
        </Button>
      </div>
    </header>
  )
}


